/*
 *  Copyright (C) 2013, Peter Decsi.
 * 
 *  This library is free software: you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public 
 *  License as published by the Free Software Foundation, either 
 *  version 3 of the License, or (at your option) any later version.
 * 
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this library.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.jreserve.grscript.gui.script.function.explorer;

import org.jreserve.grscript.gui.script.function.explorer.nodes.FunctionFolderNode;
import org.jreserve.grscript.gui.script.functions.FunctionFolder;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
        
/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.jreserve.grscript.gui.script.function.explorer//FunctionExplorer//EN",
        autostore = false)
@TopComponent.Description(
        preferredID = "FunctionExplorerTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "explorer", openAtStartup = true)
@ActionID(category = "Window", id = "org.jreserve.grscript.gui.script.function.explorer.FunctionExplorerTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_FunctionExplorerAction",
        preferredID = "FunctionExplorerTopComponent")
@Messages({
    "CTL_FunctionExplorerAction=Function Explorer",
    "CTL_FunctionExplorerTopComponent=Functions",
    "HINT_FunctionExplorerTopComponent=Browse installed functions..."
})
public final class FunctionExplorerTopComponent extends TopComponent implements ExplorerManager.Provider {

    private final static ExplorerManager em = new ExplorerManager();
    
    public FunctionExplorerTopComponent() {
        initComponents();
        setName(Bundle.CTL_FunctionExplorerTopComponent());
        setToolTipText(Bundle.HINT_FunctionExplorerTopComponent());
        initExplorerManager();
        setFocusable(true);
    }
    
    private void initExplorerManager() {
        em.setRootContext(new FunctionFolderNode(FunctionFolder.getRoot()));
        associateLookup(ExplorerUtils.createLookup(em, getActionMap()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        treeView = new org.openide.explorer.view.BeanTreeView();

        setLayout(new java.awt.BorderLayout());

        treeView.setRootVisible(false);
        add(treeView, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openide.explorer.view.BeanTreeView treeView;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
    }

    @Override
    public void componentClosed() {
    }

    void writeProperties(java.util.Properties p) {
    }

    void readProperties(java.util.Properties p) {
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return em;
    }
}
