/*
 *  Copyright (C) 2013, Peter Decsi.
 * 
 *  This library is free software: you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public 
 *  License as published by the Free Software Foundation, either 
 *  version 3 of the License, or (at your option) any later version.
 * 
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this library.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.jreserve.gui.data.actions;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.jreserve.gui.data.api.DataCategory;
import org.jreserve.gui.data.api.DataItemChooser;
import org.jreserve.gui.data.api.DataManager;
import org.jreserve.gui.misc.utils.notifications.DialogUtil;
import org.jreserve.gui.misc.utils.widgets.TextPrompt;
import org.openide.DialogDescriptor;
import org.openide.NotificationLineSupport;
import org.openide.util.NbBundle.Messages;

/**
 *
 * @author Peti
 */
@Messages({
    "LBL.CreateDataCategoryDialog.NameText.Prompt=Category Name",
    "LBL.CreateDataCategoryDialog.Title=New Data Category",
    "MSG.CreateDataCategoryDialog.Parent.Empty=Parent category not found!",
    "MSG.CreateDataCategoryDialog.Name.Empty=Name is not set!",
    "# {0} - name",
    "MSG.CreateDataCategoryDialog.Name.Exists=Name \"{0}\" already exists!",
    "# {0} - name",
    "MSG.CreateDataCategoryDialog.Name.Invalid=Name \"{0}\" is invalid!"
})
class CreateDataCategoryDialog extends javax.swing.JPanel implements DialogUtil.DialogContent {
    
    private DataManager dm;
    private TextPrompt namePrompt;
    private DialogDescriptor dd;
    private NotificationLineSupport nls;
    private NameListener textListener = new NameListener();
            
    CreateDataCategoryDialog(DataCategory parent) {
        this.dm = parent.getDataManager();
        setName(Bundle.LBL_CreateDataCategoryDialog_Title());
        initComponents();
        parentText.setText(parent.getPath());
    }
    
    @Override
    public void setDialogDescriptor(DialogDescriptor dd) {
        this.dd = dd;
        this.nls = dd.createNotificationLineSupport();
        updatePath();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        nameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        parentLabel = new javax.swing.JLabel();
        parentText = new javax.swing.JTextField();
        parentButton = new javax.swing.JButton();
        pathLabel = new javax.swing.JLabel();
        pathText = new javax.swing.JTextField();
        filler = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(400, 0), new java.awt.Dimension(32767, 32767));

        setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12));
        setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(nameLabel, org.openide.util.NbBundle.getMessage(CreateDataCategoryDialog.class, "CreateDataCategoryDialog.nameLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 5);
        add(nameLabel, gridBagConstraints);

        nameText.setText(null);
        namePrompt = TextPrompt.createStandard(Bundle.LBL_CreateDataCategoryDialog_NameText_Prompt(), nameText);
        nameText.getDocument().addDocumentListener(textListener);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        add(nameText, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(parentLabel, org.openide.util.NbBundle.getMessage(CreateDataCategoryDialog.class, "CreateDataCategoryDialog.parentLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 5);
        add(parentLabel, gridBagConstraints);

        parentText.setText(null);
        parentText.getDocument().addDocumentListener(textListener);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 5);
        add(parentText, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(parentButton, org.openide.util.NbBundle.getMessage(CreateDataCategoryDialog.class, "CreateDataCategoryDialog.parentButton.text")); // NOI18N
        parentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        add(parentButton, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(pathLabel, org.openide.util.NbBundle.getMessage(CreateDataCategoryDialog.class, "CreateDataCategoryDialog.pathLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        add(pathLabel, gridBagConstraints);

        pathText.setEditable(false);
        pathText.setText(null);
        pathText.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        add(pathText, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(filler, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void parentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentButtonActionPerformed
        DataCategory parent = DataItemChooser.chooseCategory(dm);
        if(parent != null)
            parentText.setText(parent.getPath());
    }//GEN-LAST:event_parentButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JButton parentButton;
    private javax.swing.JLabel parentLabel;
    private javax.swing.JTextField parentText;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JTextField pathText;
    // End of variables declaration//GEN-END:variables

    String getCategoryName() {
        return nameText.getText();
    }
    
    DataCategory getParentCategory() {
        String path = parentText.getText();
        
        if(path == null || path.length() == 0)
            return null;
        
        return dm.getCategory(path);
    }
    
    private void updatePath() {
        validateInput();
        
        DataCategory parent = getParentCategory();
        String name = nameText.getText();
        
        if(parent == null || name == null || name.trim().length()==0)
            pathText.setText("");
        else
          pathText.setText(parent.getPath()+"/"+name);
    }
    
    private void validateInput() {
        if(!isParentValid())
            return;
        String name = nameText.getText();
        if(nameNotEmpty(name) && nameValid(name) && nameNotExis(name))
            showError(null);
    }
    
    private boolean isParentValid() {
        if(getParentCategory() == null) {
            showError(Bundle.MSG_CreateDataCategoryDialog_Parent_Empty());
            return false;
        }
        return true;
    }
    
    private void showError(String msg) {
        if(nls != null) {
            if(msg != null) {
                nls.setErrorMessage(msg);
            } else {
                nls.clearMessages();
            }
        }
        
        if(dd != null)
            dd.setValid(msg == null);
    }
    
    private boolean nameNotEmpty(String name) {
        if(name == null || name.trim().length() == 0) {
            showError(Bundle.MSG_CreateDataCategoryDialog_Name_Empty());
            return false;
        }
        return true;
    }
    
    private boolean nameNotExis(String name) {
        DataCategory parent = getParentCategory();
        for(DataCategory child : parent.getChildCategories()) {
            if(name.equalsIgnoreCase(child.getName())) {
                showError(Bundle.MSG_CreateDataCategoryDialog_Name_Exists(name));
                return false;
            }
        }
        return true;
    }
    
    private boolean nameValid(String name) {
        if(name.indexOf('/') < 0)
            return true;
        showError(Bundle.MSG_CreateDataCategoryDialog_Name_Invalid(name));
        return false;
    }
    
    private class NameListener implements DocumentListener {

        @Override
        public void insertUpdate(DocumentEvent e) {
            updatePath();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            updatePath();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
        }
    } 
}
