/*
 *  Copyright (C) 2013, Peter Decsi.
 * 
 *  This library is free software: you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public 
 *  License as published by the Free Software Foundation, either 
 *  version 3 of the License, or (at your option) any later version.
 * 
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this library.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.jreserve.gui.excel.dataimport.template.gui;

import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.awt.ActionReferences;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
    dtd = "-//org.jreserve.gui.excel.dataimport.template.gui//ExcelTemplate//EN",
    autostore = false
)
@TopComponent.Description(
    preferredID = "ExcelTemplateTopComponent",
    iconBase="org/jreserve/gui/excel/excel.png", 
    persistenceType = TopComponent.PERSISTENCE_ONLY_OPENED
)
@TopComponent.Registration(
    mode = "explorer", 
    openAtStartup = false
)
@ActionID(
    category = "Window", 
    id = "org.jreserve.gui.excel.dataimport.template.gui.ExcelTemplateTopComponent"
)
@ActionReferences({
    @ActionReference(path = "Menu/Window", position = 60),
    @ActionReference(path = "Ribbon/TaskPanes/Windows/Utilities", position = 2000)
})
@TopComponent.OpenActionRegistration(
    displayName = "#CTL_ExcelTemplateAction",
    preferredID = "ExcelTemplateTopComponent"
)
@Messages({
    "CTL_ExcelTemplateAction=Excel Templates",
    "CTL_ExcelTemplateTopComponent=Excel Templates"
})
public final class ExcelTemplateTopComponent extends TopComponent {
    
    private final static ExplorerManager em = new ExplorerManager();

    public ExcelTemplateTopComponent() {
        initComponents();
        setName(Bundle.CTL_ExcelTemplateTopComponent());
        
        em.setRootContext(createRootNode());
        associateLookup(ExplorerUtils.createLookup(em, getActionMap()));
    }
    
    private AbstractNode createRootNode() {
        AbstractNode root = new AbstractNode(Children.LEAF);
//        AbstractNode root = new AbstractNode(Children.create(new LayerChildFactory(null), true));
//        root.setDisplayName("Layer Registration");
//        root.setIconBaseWithExtension("org/jreserve/gui/misc/layerexplorer/drive.png");
        return root;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        beanTreeView1 = new org.openide.explorer.view.BeanTreeView();

        setLayout(new java.awt.BorderLayout());

        beanTreeView1.setRootVisible(false);
        add(beanTreeView1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openide.explorer.view.BeanTreeView beanTreeView1;
    // End of variables declaration//GEN-END:variables
    
    @Override public void componentOpened() {}
    @Override public void componentClosed() {}
    void writeProperties(java.util.Properties p) {}
    void readProperties(java.util.Properties p) {}
}
