/*
 *  Copyright (C) 2013, Peter Decsi.
 * 
 *  This library is free software: you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public 
 *  License as published by the Free Software Foundation, either 
 *  version 3 of the License, or (at your option) any later version.
 * 
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this library.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.jreserve.gui.data.actions.createsourcewizard;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;
import org.jreserve.gui.data.actions.DataCategoryTreeModel;
import org.jreserve.gui.data.actions.DataCategoryTreeRenderer;
import org.jreserve.gui.data.api.DataCategory;
import org.jreserve.gui.data.api.DataManager;
import org.jreserve.gui.misc.utils.widgets.TextPrompt;
import org.netbeans.api.project.Project;
import org.netbeans.api.project.ProjectUtils;
import org.openide.util.NbBundle.Messages;

@Messages({
    "LBL.CreateDataSourceWizardVisualPanel1.Name=Step 1",
    "LBL.CreateDataSourceWizardVisualPanel1.Name.Prompt=Name of the source...",
    "MSG.CreateDataSourceWizardVisualPanel1.Parent.Empty=Parent category not selected!",
    "MSG.CreateDataSourceWizardVisualPanel1.Name.Empty=Name is not set!",
    "# {0} - name",
    "MSG.CreateDataSourceWizardVisualPanel1.Name.Exists=Name \"{0}\" already exists!",
    "MSG.CreateDataSourceWizardVisualPanel1.SourceWizard.Empty=Type not selected!"
})
class CreateDataSourceWizardVisualPanel1 extends JPanel {
    final static String PROP_NAME = "source.Name";
    final static String PROP_PARENT = "source.Parent";
    
    private DataManager dm;
    private final DataCategoryTreeModel treeModel = new DataCategoryTreeModel();
    
    private DataCategory parent;
    private String name;
    
    public CreateDataSourceWizardVisualPanel1() {
        initComponents();
        TextPrompt.createStandard(Bundle.LBL_CreateDataSourceWizardVisualPanel1_Name_Prompt(), nameText);
    }
    
    void setDataCategory(DataCategory category) {
        this.dm = category.getDataManager();
        setProjectName();
        treeModel.setDataManager(dm);
        selectCategory(category);
    }
    
    private void setProjectName() {
        Project project = dm.getProject();
        String projectName = ProjectUtils.getInformation(project).getDisplayName();
        projectText.setText(projectName);
    }
    
    private void selectCategory(DataCategory category) {
        if(category == null)
            locationTree.clearSelection();
        else
            locationTree.setSelectionPath(getPath(category));
    }
    
    private TreePath getPath(DataCategory category) {
        List<DataCategory> path = new ArrayList<DataCategory>();
        while(category != null) {
            path.add(0, category);
            category = category.getParent();
        }
        return new TreePath(path.toArray());
    }

    @Override
    public String getName() {
        return Bundle.LBL_CreateDataSourceWizardVisualPanel1_Name();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        projectLabel = new javax.swing.JLabel();
        projectText = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        typeCombo = new javax.swing.JComboBox();
        nameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        locationLabel = new javax.swing.JLabel();
        locationScroll = new javax.swing.JScrollPane();
        locationTree = new javax.swing.JTree();
        pathLabel = new javax.swing.JLabel();
        pathText = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(projectLabel, org.openide.util.NbBundle.getMessage(CreateDataSourceWizardVisualPanel1.class, "CreateDataSourceWizardVisualPanel1.projectLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        add(projectLabel, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(projectText, org.openide.util.NbBundle.getMessage(CreateDataSourceWizardVisualPanel1.class, "CreateDataSourceWizardVisualPanel1.projectText.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        add(projectText, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(typeLabel, org.openide.util.NbBundle.getMessage(CreateDataSourceWizardVisualPanel1.class, "CreateDataSourceWizardVisualPanel1.typeLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 5);
        add(typeLabel, gridBagConstraints);

        typeCombo.setModel(new DefaultComboBoxModel());
        typeCombo.setSelectedIndex(-1);
        typeCombo.addActionListener(new FactoryListener());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(typeCombo, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(nameLabel, org.openide.util.NbBundle.getMessage(CreateDataSourceWizardVisualPanel1.class, "CreateDataSourceWizardVisualPanel1.nameLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 5);
        add(nameLabel, gridBagConstraints);

        nameText.setText(null);
        nameText.getDocument().addDocumentListener(new NameListener());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(nameText, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(locationLabel, org.openide.util.NbBundle.getMessage(CreateDataSourceWizardVisualPanel1.class, "CreateDataSourceWizardVisualPanel1.locationLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 5);
        add(locationLabel, gridBagConstraints);

        locationTree.setModel(treeModel);
        locationTree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        locationTree.getSelectionModel().addTreeSelectionListener(new ParentListener());
        locationTree.setCellRenderer(new DataCategoryTreeRenderer());
        locationScroll.setViewportView(locationTree);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(locationScroll, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(pathLabel, org.openide.util.NbBundle.getMessage(CreateDataSourceWizardVisualPanel1.class, "CreateDataSourceWizardVisualPanel1.pathLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 5);
        add(pathLabel, gridBagConstraints);

        pathText.setEditable(false);
        pathText.setText(null);
        pathText.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(pathText, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel locationLabel;
    private javax.swing.JScrollPane locationScroll;
    private javax.swing.JTree locationTree;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JTextField pathText;
    private javax.swing.JLabel projectLabel;
    private javax.swing.JLabel projectText;
    private javax.swing.JComboBox typeCombo;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables

    
    private void updatePath() {
        if(parent == null || name == null || name.trim().length()==0)
            pathText.setText("");
        else
          pathText.setText(parent.getPath()+"/"+name);
    }
    
    private class FactoryListener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            DataSourceWizard wizard = (DataSourceWizard) typeCombo.getSelectedItem();
            putClientProperty(CreateDataSourceWizardIterator.PROP_SOURCE_WIZARD, wizard);
        }
    }
    
    private class NameListener implements DocumentListener {

        @Override
        public void insertUpdate(DocumentEvent e) {
            setNameProperty();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            setNameProperty();
        }
        
        private void setNameProperty() {
            name = nameText.getText();
            updatePath();
            putClientProperty(PROP_NAME, name);
        }
        
        @Override
        public void changedUpdate(DocumentEvent e) {
        }
    } 
    
    private class ParentListener implements TreeSelectionListener {
        @Override
        public void valueChanged(TreeSelectionEvent e) {
            parent = getSelectedCategory();
            updatePath();
            putClientProperty(PROP_PARENT, parent);
        }
        
        private DataCategory getSelectedCategory() {
            TreePath path = locationTree.getSelectionPath();
            if(path == null)
                return null;
            Object selection = path.getLastPathComponent();
            if(selection instanceof DataCategory)
                return (DataCategory) selection;
            return null;
        }
    }

}
