/*
 *  Copyright (C) 2013, Peter Decsi.
 * 
 *  This library is free software: you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public 
 *  License as published by the Free Software Foundation, either 
 *  version 3 of the License, or (at your option) any later version.
 * 
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this library.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.jreserve.gui.data.csv.input;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileFilter;
import javax.swing.text.JTextComponent;
import org.jreserve.gui.data.csv.settings.CsvImportSettings;
import org.jreserve.gui.localesettings.LocaleSettings;
import org.jreserve.gui.misc.utils.widgets.WidgetUtils;
import org.openide.filesystems.FileChooserBuilder;
import org.openide.util.ImageUtilities;
import org.openide.util.NbBundle.Messages;

/**
 *
 * @author Peter Decsi
 * @version 1.0
 */
@Messages({
    "LBL.CsvTableImportVisualPanel.Title=CSV Settings",
    "LBL.CsvTableImportVisualPanel.FileChooser.Title=Select CSV File"
})
public class CsvTableImportVisualPanel extends javax.swing.JPanel {
    
    private final CsvTableImportWizardPanel panel;
    private JTextComponent separatorEditor;
    private JTextComponent dateFormatEditor;
    private final InputListener inputListener = new InputListener();
    
    public CsvTableImportVisualPanel(CsvTableImportWizardPanel panel) {
        this.panel = panel;
        initComponents();
        updateExmapleDate();
    }
    
    @Override
    public String getName() {
        return Bundle.LBL_CsvTableImportVisualPanel_Title();
    }
    
    private void updateExmapleDate() {
        try {
            String str = dateFormatEditor.getText();
            SimpleDateFormat sdf = new SimpleDateFormat(str);
            dateExampleText.setText(sdf.format(new Date()));
        } catch (Exception ex) {
            dateExampleText.setText(null);
        }
    }
    
    String getCsvPath() {
        return fileText.getText();
    }
    
    boolean hasColumnHeader() {
        return columnHeaderCheck.isSelected();
    }
    
    boolean hasRowHeader() {
        return columnHeaderCheck.isSelected();
    }
    
    boolean isCellsQuoted() {
        return cellsQuotedCheck.isSelected();
    }
    
    String getCellSeparator() {
        return separatorEditor.getText();
    }
    
    String getDecimalSeparator() {
        return decimalSeparatorText.getText();
    }
    
    String getDateFormat() {
        return dateFormatEditor.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fileLabel = new javax.swing.JLabel();
        fileText = new javax.swing.JTextField();
        fileButton = new javax.swing.JButton();
        hasColumnHeaderLabel = new javax.swing.JLabel();
        columnHeaderCheck = new javax.swing.JCheckBox();
        hasRowHeaderLabel = new javax.swing.JLabel();
        rowHeaderCheck = new javax.swing.JCheckBox();
        cellsQuotedLabel = new javax.swing.JLabel();
        cellsQuotedCheck = new javax.swing.JCheckBox();
        cellSeparatorLabel = new javax.swing.JLabel();
        cellSeparatorCombo = new javax.swing.JComboBox();
        decimalSeparatorLabel = new javax.swing.JLabel();
        decimalSeparatorText = new javax.swing.JTextField();
        dateFormatLabel = new javax.swing.JLabel();
        dateFormatCombo = new javax.swing.JComboBox();
        dateExampleText = new javax.swing.JLabel();
        filler = new javax.swing.Box.Filler(new java.awt.Dimension(250, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(fileLabel, org.openide.util.NbBundle.getMessage(CsvTableImportVisualPanel.class, "CsvTableImportVisualPanel.fileLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 5);
        add(fileLabel, gridBagConstraints);

        fileText.setText(null);
        fileText.getDocument().addDocumentListener(inputListener);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 5);
        add(fileText, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(fileButton, org.openide.util.NbBundle.getMessage(CsvTableImportVisualPanel.class, "CsvTableImportVisualPanel.fileButton.text")); // NOI18N
        fileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        add(fileButton, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(hasColumnHeaderLabel, org.openide.util.NbBundle.getMessage(CsvTableImportVisualPanel.class, "CsvTableImportVisualPanel.hasColumnHeaderLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 5);
        add(hasColumnHeaderLabel, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(columnHeaderCheck, null);
        columnHeaderCheck.setSelected(CsvImportSettings.hasColumnHeaders());
        columnHeaderCheck.addActionListener(inputListener);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 5);
        add(columnHeaderCheck, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(hasRowHeaderLabel, org.openide.util.NbBundle.getMessage(CsvTableImportVisualPanel.class, "CsvTableImportVisualPanel.hasRowHeaderLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 5);
        add(hasRowHeaderLabel, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(rowHeaderCheck, null);
        rowHeaderCheck.setSelected(CsvImportSettings.hasRowHeaders());
        rowHeaderCheck.addActionListener(inputListener);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 5);
        add(rowHeaderCheck, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(cellsQuotedLabel, org.openide.util.NbBundle.getMessage(CsvTableImportVisualPanel.class, "CsvTableImportVisualPanel.cellsQuotedLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 5);
        add(cellsQuotedLabel, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(cellsQuotedCheck, null);
        cellsQuotedCheck.setSelected(CsvImportSettings.cellsQuoted());
        cellsQuotedCheck.addActionListener(inputListener);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 5);
        add(cellsQuotedCheck, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(cellSeparatorLabel, org.openide.util.NbBundle.getMessage(CsvTableImportVisualPanel.class, "CsvTableImportVisualPanel.cellSeparatorLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 5);
        add(cellSeparatorLabel, gridBagConstraints);

        cellSeparatorCombo.setEditable(true);
        cellSeparatorCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cellSeparatorCombo.setModel(new DefaultComboBoxModel(CsvImportSettings.getCellSeparators()));
        cellSeparatorCombo.setSelectedItem(CsvImportSettings.getCellSeparator());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 5);
        add(cellSeparatorCombo, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(decimalSeparatorLabel, org.openide.util.NbBundle.getMessage(CsvTableImportVisualPanel.class, "CsvTableImportVisualPanel.decimalSeparatorLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 5);
        add(decimalSeparatorLabel, gridBagConstraints);

        WidgetUtils.oneCharacterInput(decimalSeparatorText);
        decimalSeparatorText.setText(null);
        separatorEditor = (JTextComponent) cellSeparatorCombo.getEditor().getEditorComponent();
        separatorEditor.getDocument().addDocumentListener(inputListener);
        decimalSeparatorText.setText(""+LocaleSettings.getDecimalSeparator());
        decimalSeparatorText.getDocument().addDocumentListener(inputListener);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 5);
        add(decimalSeparatorText, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(dateFormatLabel, org.openide.util.NbBundle.getMessage(CsvTableImportVisualPanel.class, "CsvTableImportVisualPanel.dateFormatLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        add(dateFormatLabel, gridBagConstraints);

        dateFormatCombo.setEditable(true);
        dateFormatCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "yyyy-MM", "yyyy-MM-dd", "MM-yyyy", "dd-MM-yyyy", " " }));
        dateFormatCombo.setModel(new DefaultComboBoxModel(LocaleSettings.getDateFormats()));
        dateFormatEditor = (JTextComponent) dateFormatCombo.getEditor().getEditorComponent();
        dateFormatEditor.getDocument().addDocumentListener(inputListener);
        dateFormatCombo.setSelectedItem(LocaleSettings.getDateFormat());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 5);
        add(dateFormatCombo, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(dateExampleText, null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        add(dateExampleText, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(filler, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void fileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileButtonActionPerformed
        File f = selectFile();
        if(f != null)
            fileText.setText(f.getAbsolutePath());
    }//GEN-LAST:event_fileButtonActionPerformed
    
    private File selectFile() {
        CsvFilter filter = new CsvFilter();
        return new FileChooserBuilder(CsvTableImportVisualPanel.class)
                .setTitle(Bundle.LBL_CsvTableImportVisualPanel_FileChooser_Title())
                .setFilesOnly(true)
                .addFileFilter(filter).setFileFilter(filter)
                .showOpenDialog();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cellSeparatorCombo;
    private javax.swing.JLabel cellSeparatorLabel;
    private javax.swing.JCheckBox cellsQuotedCheck;
    private javax.swing.JLabel cellsQuotedLabel;
    private javax.swing.JCheckBox columnHeaderCheck;
    private javax.swing.JLabel dateExampleText;
    private javax.swing.JComboBox dateFormatCombo;
    private javax.swing.JLabel dateFormatLabel;
    private javax.swing.JLabel decimalSeparatorLabel;
    private javax.swing.JTextField decimalSeparatorText;
    private javax.swing.JButton fileButton;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JTextField fileText;
    private javax.swing.Box.Filler filler;
    private javax.swing.JLabel hasColumnHeaderLabel;
    private javax.swing.JLabel hasRowHeaderLabel;
    private javax.swing.JCheckBox rowHeaderCheck;
    // End of variables declaration//GEN-END:variables
    
    private static class CsvFilter extends FileFilter {

        @Override
        public boolean accept(File f) {
            if(f.isDirectory())
                return true;
            String name = f.getName();
            return name.endsWith(".csv") || name.endsWith(".CSV");
        }

        @Override
        public String getDescription() {
            return "CSV Files";
        }
    }
    
    private static class CsvBadgeProvider implements FileChooserBuilder.BadgeProvider {
        
        private final static Icon CSV_ICON = ImageUtilities.loadImageIcon("org/jreserve/gui/data/csv/csv.png", false);
        
        @Override
        public Icon getBadge(File file) {
            if(file.getName().endsWith(".csv"))
                return CSV_ICON;
            return null;
        }

        @Override
        public int getXOffset() {
            return 0;
        }

        @Override
        public int getYOffset() {
            return 0;
        }

    }
    
    private class InputListener implements ActionListener, DocumentListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            fireChange();
        }
        
        private void fireChange() {
            panel.panelChanged();
        }

        @Override
        public void insertUpdate(DocumentEvent e) {
            documentChange(e);
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            documentChange(e);
        }
        
        private void documentChange(DocumentEvent e) {
            if(e.getDocument() == dateFormatEditor.getDocument())
                updateExmapleDate();
            fireChange();
        }
        
        @Override
        public void changedUpdate(DocumentEvent e) {
        }
    }
}
